<<<<<<< Updated upstream
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Unbounded } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
const unbounded = Unbounded({
  display: 'swap',
  subsets: ["latin"],
});
export const metadata = {
  title: "Hireon",
  description: "Hireon is the best way to find job",
>>>>>>> Stashed changes
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< Updated upstream
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>
        <main>{children}</main>
        <Footer></Footer>
      </body>
=======
        className={`${unbounded.className} antialiased`}
      >
        <Header></Header>
        <main className="h-screen w-screen flex flex-col items-center">{children}</main>
{        <Footer></Footer>
}      </body>
>>>>>>> Stashed changes
    </html>
  );
}
